global using Microsoft.AspNetCore.Mvc;
global using Microsoft.Extensions.Caching.Distributed;
global using Microsoft.Extensions.Caching.Memory;
global using Microsoft.Extensions.DependencyInjection.Extensions;
global using NetCoreRedisTalks.Caching.Infrastructure;
global using NetCoreRedisTalks.Caching.Models;
global using StackExchange.Redis;
global using System.Text;
global using System.Text.Json;
